# Generated by Django 3.2.5 on 2021-07-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='IngredientCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории ингредиента', max_length=50, verbose_name='Категория ингредиента')),
            ],
            options={
                'verbose_name': 'Категории ингредиентов',
                'verbose_name_plural': 'Категории ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ведите название ингредиента', max_length=50, verbose_name='Ингредиент')),
                ('icon', models.ImageField(help_text='Иконка', upload_to='icon_ingredient/', verbose_name='Иконка')),
                ('category', models.ForeignKey(help_text='Выберите категорию ингредиента', on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='catalog.ingredientcategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок поста', max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст поста', verbose_name='Содержимое поста')),
                ('preview', models.ImageField(help_text='Изображение', upload_to='preview_post/', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ведите название рецепта', max_length=100, verbose_name='Название')),
                ('summary', models.TextField(help_text='Введите описание приготовления блюда', verbose_name='Приготовление')),
                ('calories', models.CharField(help_text='Кол-во калорий', max_length=40, verbose_name='Калории')),
                ('cooking_time', models.CharField(help_text='Время приготовления', max_length=20, verbose_name='Время приготовления')),
                ('preview', models.ImageField(help_text='Изображение', upload_to='main_picture/', verbose_name='Основное изображение')),
                ('category', models.ManyToManyField(help_text='Выберите категории', to='catalog.Categories', verbose_name='Категории')),
                ('ingredient', models.ManyToManyField(help_text='Выберите ингредиенты', to='catalog.Ingredients', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
