# Generated by Django 3.2.5 on 2021-11-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210905_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.ManyToManyField(blank=True, to='catalog.Ip'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='views',
            field=models.ManyToManyField(blank=True, to='catalog.Ip'),
        ),
    ]
